[project]
name = "data-projects-lab"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11,<3.12"
dependencies = [
    "flaml[automl]>=2.3.6",
    "ipykernel>=7.0.1",
    "matplotlib>=3.7.5",
    "nbconvert>=7.16.6",
    "pandas>=2.1.0,<2.2.0",
    "path>=17.1.1",
    "plotly>=5.5.0,<6.0.0",
    "pyarrow>=21.0.0",
    "pycaret>=3.3.0",
    "scikit-learn>=1.3.0,<1.6.0",
    "seaborn>=0.13.2",
]
